### ISSUE TITLE
请问是否可以引用此主题？

### ISSUE THREAD

**Issue by txperl** [Twor/hugo-angus#1]
翻了一下以前的 Issues，看到你发的想要移植 Story 的想法。点进来一看，哇原来早就完成了。

真的很高兴你能喜欢，而且写下了有着自己见解的 Hugo 版本。

不知道可不可以，我想将此版本放入这个 [Forks](https://github.com/txperl/Story-for-Typecho/tree/2d43717a308de11b345fc40cbb82d06dcbce4b6d#forks) 列表中，让大家可以看到新的不一样的主题实现。

(⊙ꇴ⊙)

**Comment by Twor** [comment]
当然可以，这是我的荣幸。抱歉最近没有频繁访问github，回复比较晚

**Comment by txperl** [comment]
已经更新了，谢谢啦。

😊
